<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="C02NK0ZQG3QT.local" name="test 2" tests="1" failures="1" timestamp="24 Aug 2015 12:40:54 GMT" time="11.625" errors="0">
  <testcase name="run" time="8.977" classname="Hoteling.archHotel.jbehave.AcceptanceTestSuite">
    <failure type="org.jbehave.core.embedder.Embedder$RunningStoriesFailed" message="Failures in running stories: ReportsCount[stories=1,storiesNotAllowed=0,storiesPending=0,scenarios=1,scenariosFailed=1,scenariosNotAllowed=0,scenariosPending=0,stepsFailed=1]">
      <![CDATA[org.jbehave.core.embedder.Embedder$RunningStoriesFailed: Failures in running stories: ReportsCount[stories=1,storiesNotAllowed=0,storiesPending=0,scenarios=1,scenariosFailed=1,scenariosNotAllowed=0,scenariosPending=0,stepsFailed=1]
	at org.jbehave.core.embedder.Embedder$ThrowingRunningStoriesFailed.handleFailures(Embedder.java:525)
	at org.jbehave.core.embedder.Embedder.handleFailures(Embedder.java:269)
	at org.jbehave.core.embedder.Embedder.generateReportsView(Embedder.java:256)
	at org.jbehave.core.embedder.Embedder.generateReportsView(Embedder.java:237)
	at org.jbehave.core.embedder.Embedder.runStoriesAsPaths(Embedder.java:213)
	at org.jbehave.core.junit.JUnitStories.run(JUnitStories.java:20)
	at Hoteling.archHotel.jbehave.AcceptanceTestSuite.run(AcceptanceTestSuite.java:30)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
... Removed 16 stack frames]]>
    </failure>
  </testcase> <!-- run -->
</testsuite> <!-- test 2 -->
